/*modelagem basica*/

CLIENTE

NOME - CARACTER (50)
SEXO - CARACTER (1)
EMAIL - (50)
CPF - NUMERICO (11)
TELEFONE - NUMERICO (15)
ENDERECO - CARACTER (50)

/*processos de modelagens*/

/*as duas primeiras fases */
MODELAGEM CONCEITUAL = RASCUNHO
MODELAGEM LOGICA = QUALQUER PROGRAMA DE MODELAGEM


/*FASE 3 É FEITO PELO DBA, MAS TAMBEM PODE SER FEITO PELO AD*/

MODELAGEM FISICA = SCRIPTS DO BANCO




/* sintax basica de insercao -INSERT INTO TABELA...    ESSE COMANDO SERVE PARA TODOS OS TIPOS DE BANCO DE DADOS*/

/* FORMA 01 - OMITINDO as colunas*/

INSERT INTO CLIENTE VALUES ('JOAO', 'M', 'JOAO@EMAIL.COM', 988638273, '22923110', 'MAIA LACERDA ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES ('CELIA', 'F', 'CELIA@EMAIL.COM', 541521456, '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES ('JORGE', 'M', NULL, 885755836, '58748895', 'OSCAR URY - BOM RETIRO - PATOS DE MINAS - MG');

/*FORMA 2 - COLOCANDO AS COLUNAS*/

/*ESSA SEGUNDA FORMA É A MAIS RECOMENDADA POR EVTAR ERROS DE POSICIONAMENTO DOS DADOS QUANDO DIGITADOS*/

INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES('LILIAN', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '947785696', 887774856);

/*FORMA 3 - INSERT COMPACTO - SOMENTE MYSQL*/

INSERT INTO CLIENTE VALUES('CARLA', 'F', 'CARLA@TERATI.COM.BR', 7745828, '66587458', 'SAMUEL SILVA - CENTRO - BELO HORIZONTE'),
    ('ANA', 'F', 'ANA@GLOBO.COM', 85548962, '588556985', 'PRES ANTONIO CARLOS - CENTRO - SAO PAULO'); 

INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES('CLARA', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '947785655', 123456789654);

INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES('CLARA', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '947785655', 22222222222);



/*COMANDO SELECT*/
/*selecao projecao e juncao*/


SELECT NOW();

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';


EX: SELECT NOW() AS DATA_HORA, 'FELIPE MAFRA' AS PROFESSOR;

/*ALIAS DE COLUNAS*/

SELECT NOME, SEXO, EMAIL FROM CLIENTE;


/*aula 23- selecoes*/

/*trabalhando com filtros*/


RELEMBRANDO - SE EU USO SELECT EU ESTOU PROJETANDO - TRAZENDO A COLUNA INTEIRA, 
E USANDO AS SELECOES ELE FILTRA POR LINHAS E NAO COLUNAS.

PARA PROJECAO USAMOS - SELECT
PARA SELECAO USAMOS - WHERE

/*FILTRANDO*/

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';

/*USANDO LIKE*/

/*A PALAVRA LIKE SUBSTITUI O SINAL DE IGUALDADE (=) E NAO SE USA JAMAIS LIKE COM =  EX: = LIKE OU LIKE = */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

/*CARACTER CORINGA % -> QUALQUER COISA*/

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE 'OSCAR URY%';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%CENTRO%';

-- Or
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO, FROM CLIENTE
WHERE SEXO = 'F' OR ENDERECO LIKE '%ESTACIO'

-- AND

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'F' AND ENDERECO LIKE '%ESTACIO';